#!/bin/sh
if [ $# -eq 0 ]
then
	echo "Usage: $0 -p user:project [-r] [-d JMXPORT]"
	exit 1
fi
while getopts  :p:rd: OPTION; do

    case $OPTION in
        p)
            GIT=$(echo $OPTARG|awk -F ':'  '{print $2}')
            GITUSER=$(echo $OPTARG|awk -F ':'   '{print $1}')
            if [[ -z $GIT || -z $GITUSER ]] ; then
                echo "Usage: $0 -p user:project [-r] [-d JMXPORT]"
                echo "project not exis"
            fi
            #PROJECT=$(echo "$OPTARG" | sed 's/\.git$//');
        ;;
        r)
            RESET="1";
        ;;
        d)
            JMXPORT=$OPTARG;
            if [[ $JMXPORT -le 0 ]] ; then
                echo "DEBUG port invalid."
                exit;
            fi
        ;;
        ?)
            echo "illegal option $OPTION $OPTARG"
            exit 1;;

    esac;
done
pullgit -p $GIT -u $GITUSER
ROOT_PATH=$(env|grep HOME|awk -F '='   '{print $2}')"/IdeaProjects"
PROJECT=$(echo "$GIT" | sed 's/\.git$//');
PROJECTFIXED="${PROJECT}.git"


if [[ ! -f "$ROOT_PATH/${GITUSER}/${PROJECTFIXED}/pom.xml" ]] ;then
    echo "不是java项目无法运行"
    echo "$ROOT_PATH/${GITUSER}/${PROJECTFIXED}/pom.xml不存在"
    exit;
fi

echo "工作目录${ROOT_PATH}"
echo "切换到目录${GITUSER}/${PROJECTFIXED}"

cd "$ROOT_PATH/${GITUSER}/${PROJECTFIXED}"
if [[ $RESET == "1" ]] ; then
        echo "清理项目"
        mvn clean
fi
if [[ -f "$ROOT_PATH/${GITUSER}/$PROJECTFIXED/project.properties" ]] ; then
    INSTALL=$(cat project.properties|awk -F "=" '{print $2}')
else
    INSTALL=0;
fi

if [[ $INSTALL  == 1 ]] ; then
    echo "安装到maven"
    mvn install
else
    echo "运行java"
    PIDINFO=`/usr/bin/jps -l | /usr/bin/grep $PROJECT`
    PID=`echo ${PIDINFO}|awk '{print $1}'`
    echo "停止原来项目PID ${PID}"
    kill  $PID
    echo "编译项目"
    mvn package
    cd target
    if [[ $JMXPORT -gt 0 ]] ;then
        if [[ `netstat -tnl|grep $JMXPORT|wc -l` -gt 0 ]] ; then
            echo "在端口${JMXPORT}上启动调试失败，以常规方式启动"
            /usr/bin/nohup /usr/bin/java -jar -Dspring.cloud.config.profile=prod  $PROJECT.jar >/dev/null 2>&1 &
        else
            /usr/bin/nohup /usr/bin/java -Dcom.sun.management.jmxremote.port=$JMXPORT -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -jar -Dspring.cloud.config.profile=prod  $PROJECT.jar >/dev/null 2>&1 &
        fi
    else
            /usr/bin/nohup /usr/bin/java -jar -Dspring.cloud.config.profile=prod  $PROJECT.jar >/dev/null 2>&1 &
    fi
    #str=$"\n"
    #sstr=$(echo -e $str)
    #echo $sstr
    #tail -f nohup.out
fi
