#!/bin/sh
BASEPATH=$(cd `dirname $0`; pwd)
REPOS=`cat ${BASEPATH}/.gitrepo`
echo "即将更新如下git $REPOS"
for GITINFO in $REPOS; do
  GIT=$(echo $GITINFO|awk -F ':'   '{print $2}')



  GITUSER=$(echo $GITINFO|awk -F ':'   '{print $1}')
  pullgit -p $GIT -u $GITUSER
done
