#!/bin/sh
if [ $# -eq 0 ]
then
	echo "Usage: $0 -p project -u guliuzhong"
	exit 1
fi
while getopts  :p:u:l: OPTION; do

    case $OPTION in
        p)
            PROJECT=$(echo "$OPTARG" | sed 's/\.git$//');
        ;;
        u)
            U=$(echo "$OPTARG");
        ;;
	l)
	    L=$(echo "$OPTARG");
	;;
        ?)
            echo "illegal option $OPTION $OPTARG"
            exit 1;;

    esac;
done

echo $L;

PROJECTFIXED="${PROJECT}.git"
ROOT_PATH=$(env|grep HOME|awk -F '='   '{print $2}')"/"${L:-"git_local_path"}
echo -e "根目录路径为\033[31;5m ${ROOT_PATH} \033[0m"

if [[ ! -d "$ROOT_PATH/${U}/${PROJECTFIXED}" ]] ; then
	mkdir -p "$ROOT_PATH/${U}/${PROJECTFIXED}"
	cd "$ROOT_PATH/${U}/${PROJECTFIXED}"
	echo "版本库地址 git@gitee.com:${U}/${PROJECTFIXED}"
	git clone "git@gitee.com:/${U}/${PROJECTFIXED}" ./
fi
if [[ ! -d "$ROOT_PATH/${U}/${PROJECTFIXED}/.git" ]] ;then
    echo "项目不存在,删除check文件"
    rm -frv "$ROOT_PATH/${U}/${PROJECTFIXED}"
    exit;
fi
cd "$ROOT_PATH/${U}/${PROJECTFIXED}"

git pull -p
git submodule update
echo "更新项目完成"
