#!/bin/sh
if [ $# -eq 0 ]
then
	echo "Usage: $0 -p project -u guliuzhong"
	exit 1
fi
while getopts  :p:u: OPTION; do

    case $OPTION in
        p)
            PROJECT=$(echo "$OPTARG" | sed 's/\.git$//');
        ;;
        u)
            U=$(echo "$OPTARG");
        ;;
        ?)
            echo "illegal option $OPTION $OPTARG"
            exit 1;;

    esac;
done
PROJECTFIXED="${PROJECT}.git"
ROOT_PATH=$(env|grep HOME|awk -F '='   '{print $2}')"/IdeaProjects"
echo -e "根目录路径为\033[31;5m ${ROOT_PATH} \033[0m"
pullgit -p ${PROJECTFIXED}-u ${U}
if [[ ! -d "$ROOT_PATH/${U}/${PROJECTFIXED}" ]] ; then
	echo -e "项目不存在"
	exit
fi
git remote add github git@github.com:${U}/${PROJECTFIXED}
cd "$ROOT_PATH/${U}/${PROJECTFIXED}"
echo "更新最新代码"
git fetch origin --prune -v 
echo "推送github"
git push github --prune --mirror -v
echo "完成更新 $1"
